2019-01-20 13:30:25,387 [cheetah][Thread:41][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.Web.HttpException (0x80004005): Cannot redirect after HTTP headers have been sent.
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)
   at Sphdhv.DnnWebApi.Controllers.AuthenticationController.<VerifyToken>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2019-01-20 13:30:25,481 [cheetah][Thread:41][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.Web.HttpException (0x80004005): Cannot redirect after HTTP headers have been sent.
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)
   at Sphdhv.DnnWebApi.Controllers.AuthenticationController.<VerifyToken>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2019-01-20 13:30:25,512 [cheetah][Thread:36][FATAL] DotNetNuke.Web.Common.Internal.DotNetNukeHttpApplication - System.Web.HttpException (0x80004005): Server cannot set status after HTTP headers have been sent.
   at System.Web.HttpResponse.set_StatusCode(Int32 value)
   at System.Web.Http.WebHost.HttpControllerHandler.<CopyResponseStatusAndHeadersAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.WebHost.HttpControllerHandler.<CopyResponseAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.WebHost.HttpControllerHandler.<ProcessRequestAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at System.Web.HttpApplication.CallHandlerExecutionStep.InvokeEndHandler(IAsyncResult ar)
   at System.Web.HttpApplication.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar)
2019-01-20 14:11:03,985 [cheetah][Thread:40][FATAL] DotNetNuke.Framework.PageBase - An error has occurred while loading page.
System.Web.HttpException (0x80004005): Validation of viewstate MAC failed. If this application is hosted by a Web Farm or cluster, ensure that <machineKey> configuration specifies the same validationKey and validation algorithm. AutoGenerate cannot be used in a cluster.

See http://go.microsoft.com/fwlink/?LinkID=314055 for more information. ---> System.Web.UI.ViewStateException: Invalid viewstate. 
	Client IP: 10.2.20.246
	Port: 13722
	Referer: 
	Path: /Default.aspx
	User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
	ViewState: ga QYx25UfM77vVEvBpDNb72bCpslufj3Z/AvOjINjyCYH2EXPh6bLjtjyw06y71xXRr/tPPGA9P2mBJS0Ec2GgQtkDKiA0cqLsYdL4/zVgw4Jy8w y1Yi5myoezPZ1kuXnveqFJTWMXKWTH1vt 5IFNIWurzEX7qFwJFZ0wGqONG887JwgPX5esv9r1kUmLtSDR7WMyZQ 4QzJNCaw2hPs0LJR0UdJyFe0AGAc2GwkuxXysfjj27ZBNzzVyFvaABLxF76AddIL2wiX7/8UvuGB8uXdCXiyMGqEzNEFA npkEWGYGc3Mi0KPUUOd8MCRgeZVmwB9bds3LDzFB47CrgQDwx4/Td9hUmXY j 35xDfvHROu/kDxZckyQWKBbK3YEJn6A==
   at System.Web.UI.ViewStateException.ThrowError(Exception inner, String persistedState, String errorPageMessage, Boolean macValidationError)
   at System.Web.UI.ObjectStateFormatter.Deserialize(String inputString, Purpose purpose)
   at System.Web.UI.Util.DeserializeWithAssert(IStateFormatter2 formatter, String serializedState, Purpose purpose)
   at System.Web.UI.HiddenFieldPageStatePersister.Load()
   at System.Web.UI.Page.LoadPageStateFromPersistenceMedium()
   at System.Web.UI.Page.LoadAllState()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
2019-01-20 14:11:04,001 [cheetah][Thread:40][ERROR] DotNetNuke.Services.Exceptions.Exceptions - ~/Default.aspx?tabid=243&error=An unexpected error has occurred&content=0
System.Web.HttpException (0x80004005): Validation of viewstate MAC failed. If this application is hosted by a Web Farm or cluster, ensure that <machineKey> configuration specifies the same validationKey and validation algorithm. AutoGenerate cannot be used in a cluster.

See http://go.microsoft.com/fwlink/?LinkID=314055 for more information. ---> System.Web.UI.ViewStateException: Invalid viewstate. 
	Client IP: 10.2.20.246
	Port: 13722
	Referer: 
	Path: /Default.aspx
	User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
	ViewState: ga QYx25UfM77vVEvBpDNb72bCpslufj3Z/AvOjINjyCYH2EXPh6bLjtjyw06y71xXRr/tPPGA9P2mBJS0Ec2GgQtkDKiA0cqLsYdL4/zVgw4Jy8w y1Yi5myoezPZ1kuXnveqFJTWMXKWTH1vt 5IFNIWurzEX7qFwJFZ0wGqONG887JwgPX5esv9r1kUmLtSDR7WMyZQ 4QzJNCaw2hPs0LJR0UdJyFe0AGAc2GwkuxXysfjj27ZBNzzVyFvaABLxF76AddIL2wiX7/8UvuGB8uXdCXiyMGqEzNEFA npkEWGYGc3Mi0KPUUOd8MCRgeZVmwB9bds3LDzFB47CrgQDwx4/Td9hUmXY j 35xDfvHROu/kDxZckyQWKBbK3YEJn6A==
   at System.Web.UI.ViewStateException.ThrowError(Exception inner, String persistedState, String errorPageMessage, Boolean macValidationError)
   at System.Web.UI.ObjectStateFormatter.Deserialize(String inputString, Purpose purpose)
   at System.Web.UI.Util.DeserializeWithAssert(IStateFormatter2 formatter, String serializedState, Purpose purpose)
   at System.Web.UI.HiddenFieldPageStatePersister.Load()
   at System.Web.UI.Page.LoadPageStateFromPersistenceMedium()
   at System.Web.UI.Page.LoadAllState()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
2019-01-20 14:11:12,970 [cheetah][Thread:42][FATAL] DotNetNuke.Framework.PageBase - An error has occurred while loading page.
System.Web.HttpException (0x80004005): The state information is invalid for this page and might be corrupted. ---> System.Web.UI.ViewStateException: Invalid viewstate. 
	Client IP: 10.2.20.246
	Port: 20870
	Referer: 
	Path: /Default.aspx
	User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
	ViewState: 2MpEgZV36/JxyevNtXJk0JsRjCKEklgFj0lMmWQOeccPyKm0ax39ehFIipg8bRQmcG7xaiUd4TnUELzl0e0 2o4KXH535fKJaIFICA== ---> System.FormatException: Invalid length for a Base-64 char array or string.
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at System.Web.UI.ObjectStateFormatter.Deserialize(String inputString, Purpose purpose)
   at System.Web.UI.Util.DeserializeWithAssert(IStateFormatter2 formatter, String serializedState, Purpose purpose)
   at System.Web.UI.HiddenFieldPageStatePersister.Load()
   --- End of inner exception stack trace ---
   at System.Web.UI.ViewStateException.ThrowError(Exception inner, String persistedState, String errorPageMessage, Boolean macValidationError)
   at System.Web.UI.HiddenFieldPageStatePersister.Load()
   at System.Web.UI.Page.LoadPageStateFromPersistenceMedium()
   at System.Web.UI.Page.LoadAllState()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
2019-01-20 14:11:12,970 [cheetah][Thread:42][ERROR] DotNetNuke.Services.Exceptions.Exceptions - ~/Default.aspx?tabid=426&error=An unexpected error has occurred&content=0
System.Web.HttpException (0x80004005): The state information is invalid for this page and might be corrupted. ---> System.Web.UI.ViewStateException: Invalid viewstate. 
	Client IP: 10.2.20.246
	Port: 20870
	Referer: 
	Path: /Default.aspx
	User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
	ViewState: 2MpEgZV36/JxyevNtXJk0JsRjCKEklgFj0lMmWQOeccPyKm0ax39ehFIipg8bRQmcG7xaiUd4TnUELzl0e0 2o4KXH535fKJaIFICA== ---> System.FormatException: Invalid length for a Base-64 char array or string.
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at System.Web.UI.ObjectStateFormatter.Deserialize(String inputString, Purpose purpose)
   at System.Web.UI.Util.DeserializeWithAssert(IStateFormatter2 formatter, String serializedState, Purpose purpose)
   at System.Web.UI.HiddenFieldPageStatePersister.Load()
   --- End of inner exception stack trace ---
   at System.Web.UI.ViewStateException.ThrowError(Exception inner, String persistedState, String errorPageMessage, Boolean macValidationError)
   at System.Web.UI.HiddenFieldPageStatePersister.Load()
   at System.Web.UI.Page.LoadPageStateFromPersistenceMedium()
   at System.Web.UI.Page.LoadAllState()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
2019-01-20 14:36:14,644 [cheetah][Thread:40][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource niet gevonden: - 
System.Web.HttpException (0x80004005): Resource niet gevonden
2019-01-20 14:49:24,162 [cheetah][Thread:27][FATAL] DotNetNuke.Web.Common.Internal.DotNetNukeHttpApplication - System.Web.HttpException (0x80004005): Server cannot set status after HTTP headers have been sent.
   at System.Web.HttpResponse.set_StatusCode(Int32 value)
   at System.Web.Http.WebHost.HttpControllerHandler.<CopyResponseStatusAndHeadersAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.WebHost.HttpControllerHandler.<CopyResponseAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.WebHost.HttpControllerHandler.<ProcessRequestAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at System.Web.HttpApplication.CallHandlerExecutionStep.InvokeEndHandler(IAsyncResult ar)
   at System.Web.HttpApplication.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar)
2019-01-20 15:03:34,788 [cheetah][Thread:15][FATAL] DotNetNuke.Framework.PageBase - An error has occurred while loading page.
System.Web.HttpException (0x80004005): The state information is invalid for this page and might be corrupted. ---> System.Web.UI.ViewStateException: Invalid viewstate. 
	Client IP: 10.2.20.246
	Port: 65049
	Referer: 
	Path: /Default.aspx
	User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
	ViewState: E0AoWo8gx19KTXvXCFv70mlRerQuC4JVzCoCVOSwcEc6v2WvcWC2 oVt1YT7qk/Kv6aH4 VKkgMj38kI HTxyuzgImJYQS mRgs40hhR3HZ7bSdM/pINqy8dqgGbEbZbvVK3LxF7A8qNGpZUgxzcMt LfVnlDOTSQNGpq06anSlLnsLnpbeitFtN4haiY4EofSSslhOhxCUiB/xJ46mR50kMKWTrH1UuHX8 splGBEi1JAEGCH aBONLEaMYHDDcFD8X4fpg271VGRMPg280gzJ3ibwbHdPHwQ NFEXdcMBe/NhGhLV4B3KYsgg 4a6sg8ROQa/EIZoWNBhvBW5txvFJ2Uwk4LX NpqEEBrkjNQAQqKp/fs0YbnBWYZMe9/gLVXVww== ---> System.FormatException: Invalid length for a Base-64 char array or string.
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at System.Web.UI.ObjectStateFormatter.Deserialize(String inputString, Purpose purpose)
   at System.Web.UI.Util.DeserializeWithAssert(IStateFormatter2 formatter, String serializedState, Purpose purpose)
   at System.Web.UI.HiddenFieldPageStatePersister.Load()
   --- End of inner exception stack trace ---
   at System.Web.UI.ViewStateException.ThrowError(Exception inner, String persistedState, String errorPageMessage, Boolean macValidationError)
   at System.Web.UI.HiddenFieldPageStatePersister.Load()
   at System.Web.UI.Page.LoadPageStateFromPersistenceMedium()
   at System.Web.UI.Page.LoadAllState()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
2019-01-20 15:03:34,788 [cheetah][Thread:15][ERROR] DotNetNuke.Services.Exceptions.Exceptions - ~/Default.aspx?tabid=243&error=An unexpected error has occurred&content=0
System.Web.HttpException (0x80004005): The state information is invalid for this page and might be corrupted. ---> System.Web.UI.ViewStateException: Invalid viewstate. 
	Client IP: 10.2.20.246
	Port: 65049
	Referer: 
	Path: /Default.aspx
	User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
	ViewState: E0AoWo8gx19KTXvXCFv70mlRerQuC4JVzCoCVOSwcEc6v2WvcWC2 oVt1YT7qk/Kv6aH4 VKkgMj38kI HTxyuzgImJYQS mRgs40hhR3HZ7bSdM/pINqy8dqgGbEbZbvVK3LxF7A8qNGpZUgxzcMt LfVnlDOTSQNGpq06anSlLnsLnpbeitFtN4haiY4EofSSslhOhxCUiB/xJ46mR50kMKWTrH1UuHX8 splGBEi1JAEGCH aBONLEaMYHDDcFD8X4fpg271VGRMPg280gzJ3ibwbHdPHwQ NFEXdcMBe/NhGhLV4B3KYsgg 4a6sg8ROQa/EIZoWNBhvBW5txvFJ2Uwk4LX NpqEEBrkjNQAQqKp/fs0YbnBWYZMe9/gLVXVww== ---> System.FormatException: Invalid length for a Base-64 char array or string.
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at System.Web.UI.ObjectStateFormatter.Deserialize(String inputString, Purpose purpose)
   at System.Web.UI.Util.DeserializeWithAssert(IStateFormatter2 formatter, String serializedState, Purpose purpose)
   at System.Web.UI.HiddenFieldPageStatePersister.Load()
   --- End of inner exception stack trace ---
   at System.Web.UI.ViewStateException.ThrowError(Exception inner, String persistedState, String errorPageMessage, Boolean macValidationError)
   at System.Web.UI.HiddenFieldPageStatePersister.Load()
   at System.Web.UI.Page.LoadPageStateFromPersistenceMedium()
   at System.Web.UI.Page.LoadAllState()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
2019-01-20 15:03:37,976 [cheetah][Thread:28][FATAL] DotNetNuke.Framework.PageBase - An error has occurred while loading page.
System.Web.HttpException (0x80004005): The state information is invalid for this page and might be corrupted. ---> System.Web.UI.ViewStateException: Invalid viewstate. 
	Client IP: 10.2.20.246
	Port: 10952
	Referer: 
	Path: /Default.aspx
	User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
	ViewState: jube1dQViajZJGc/AvLkTVzMHcLtG4MEtB92NrxxGkuc2oY8p5aY0TE GM/Lr6qLHkD8e4 JmcQN9tUFP5Krn2j3oArPSEFqzafp8w== ---> System.FormatException: Invalid length for a Base-64 char array or string.
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at System.Web.UI.ObjectStateFormatter.Deserialize(String inputString, Purpose purpose)
   at System.Web.UI.Util.DeserializeWithAssert(IStateFormatter2 formatter, String serializedState, Purpose purpose)
   at System.Web.UI.HiddenFieldPageStatePersister.Load()
   --- End of inner exception stack trace ---
   at System.Web.UI.ViewStateException.ThrowError(Exception inner, String persistedState, String errorPageMessage, Boolean macValidationError)
   at System.Web.UI.HiddenFieldPageStatePersister.Load()
   at System.Web.UI.Page.LoadPageStateFromPersistenceMedium()
   at System.Web.UI.Page.LoadAllState()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
2019-01-20 15:03:37,976 [cheetah][Thread:28][ERROR] DotNetNuke.Services.Exceptions.Exceptions - ~/Default.aspx?tabid=426&error=An unexpected error has occurred&content=0
System.Web.HttpException (0x80004005): The state information is invalid for this page and might be corrupted. ---> System.Web.UI.ViewStateException: Invalid viewstate. 
	Client IP: 10.2.20.246
	Port: 10952
	Referer: 
	Path: /Default.aspx
	User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
	ViewState: jube1dQViajZJGc/AvLkTVzMHcLtG4MEtB92NrxxGkuc2oY8p5aY0TE GM/Lr6qLHkD8e4 JmcQN9tUFP5Krn2j3oArPSEFqzafp8w== ---> System.FormatException: Invalid length for a Base-64 char array or string.
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at System.Web.UI.ObjectStateFormatter.Deserialize(String inputString, Purpose purpose)
   at System.Web.UI.Util.DeserializeWithAssert(IStateFormatter2 formatter, String serializedState, Purpose purpose)
   at System.Web.UI.HiddenFieldPageStatePersister.Load()
   --- End of inner exception stack trace ---
   at System.Web.UI.ViewStateException.ThrowError(Exception inner, String persistedState, String errorPageMessage, Boolean macValidationError)
   at System.Web.UI.HiddenFieldPageStatePersister.Load()
   at System.Web.UI.Page.LoadPageStateFromPersistenceMedium()
   at System.Web.UI.Page.LoadAllState()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
2019-01-20 15:22:33,275 [cheetah][Thread:48][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:22:33,947 [cheetah][Thread:42][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:22:34,619 [cheetah][Thread:47][ERROR] DotNetNuke.Entities.Urls.UrlRewriterUtils - System.Exception: Illegal request exception : TabId parameters in query string, but invalid TabId requested : https://www.pensioenfondshaskoningdhv.nl/LinkClick.aspx?fileticket=cNoEITV4h2g=&portalid=1&mid=771&language=en-US&tabid=%2f**%2fcOnVeRt(int%2c(char(33)%2bchar(126)%2bchar(33)%2b(char(65)%2bchar(66)%2bchar(67)%2bchar(49)%2bchar(52)%2bchar(53)%2bchar(90)%2bchar(81)%2bchar(54)%2bchar(50)%2bchar(68)%2bchar(87)%2bchar(81)%2bchar(65)%2bchar(70)%2bchar(80)%2bchar(79)%2bchar(73)%2bchar(89)%2bchar(67)%2bchar(70)%2bchar(68))%2bchar(33)%2bchar(126)%2bchar(33)))
2019-01-20 15:22:35,197 [cheetah][Thread:31][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:22:37,447 [cheetah][Thread:42][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:22:39,384 [cheetah][Thread:42][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:22:41,353 [cheetah][Thread:46][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:22:42,025 [cheetah][Thread:46][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:22:43,994 [cheetah][Thread:47][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:22:44,712 [cheetah][Thread:48][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:22:45,400 [cheetah][Thread:44][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:22:46,072 [cheetah][Thread:47][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:22:46,728 [cheetah][Thread:31][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:22:47,400 [cheetah][Thread:44][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:22:48,056 [cheetah][Thread:31][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:22:48,728 [cheetah][Thread:44][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:38:45,167 [cheetah][Thread:26][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:38:45,355 [cheetah][Thread:26][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:38:45,652 [cheetah][Thread:26][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:38:46,089 [cheetah][Thread:24][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:38:46,464 [cheetah][Thread:35][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:38:46,996 [cheetah][Thread:24][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:38:47,136 [cheetah][Thread:32][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:38:47,652 [cheetah][Thread:24][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:38:47,902 [cheetah][Thread:32][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:38:48,074 [cheetah][Thread:24][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:38:48,261 [cheetah][Thread:32][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:38:48,417 [cheetah][Thread:26][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:38:48,589 [cheetah][Thread:26][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:38:48,777 [cheetah][Thread:32][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:38:48,949 [cheetah][Thread:32][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:57:39,420 [cheetah][Thread:81][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:57:40,092 [cheetah][Thread:81][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:57:41,217 [cheetah][Thread:84][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:57:43,123 [cheetah][Thread:72][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:57:45,029 [cheetah][Thread:81][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:57:46,998 [cheetah][Thread:85][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:57:47,623 [cheetah][Thread:72][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:57:49,576 [cheetah][Thread:85][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:57:50,279 [cheetah][Thread:72][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:57:50,904 [cheetah][Thread:85][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:57:51,529 [cheetah][Thread:84][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:57:52,154 [cheetah][Thread:84][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:57:52,779 [cheetah][Thread:72][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:57:53,404 [cheetah][Thread:72][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 15:57:54,060 [cheetah][Thread:72][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:16:18,844 [cheetah][Thread:53][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:16:19,422 [cheetah][Thread:24][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:16:20,469 [cheetah][Thread:21][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:16:22,297 [cheetah][Thread:10][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:16:23,844 [cheetah][Thread:21][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:16:25,422 [cheetah][Thread:53][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:16:25,984 [cheetah][Thread:10][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:16:27,484 [cheetah][Thread:24][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:16:28,188 [cheetah][Thread:21][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:16:28,797 [cheetah][Thread:71][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:16:29,359 [cheetah][Thread:10][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:16:29,922 [cheetah][Thread:21][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:16:30,500 [cheetah][Thread:53][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:16:31,062 [cheetah][Thread:21][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:16:31,625 [cheetah][Thread:24][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:35:51,096 [cheetah][Thread:21][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:35:51,299 [cheetah][Thread:10][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:35:51,518 [cheetah][Thread:71][ERROR] DotNetNuke.Entities.Urls.UrlRewriterUtils - System.Exception: Illegal request exception : TabId parameters in query string, but invalid TabId requested : https://www.pensioenfondshaskoningdhv.nl/LinkClick.aspx?fileticket=cNoEITV4h2g=&portalid=1&mid=771&language=en-US&tabid=%2f**%2fcOnVeRt(int%2c(char(33)%2bchar(126)%2bchar(33)%2b(char(65)%2bchar(66)%2bchar(67)%2bchar(49)%2bchar(52)%2bchar(53)%2bchar(90)%2bchar(81)%2bchar(54)%2bchar(50)%2bchar(68)%2bchar(87)%2bchar(81)%2bchar(65)%2bchar(70)%2bchar(80)%2bchar(79)%2bchar(73)%2bchar(89)%2bchar(67)%2bchar(70)%2bchar(68))%2bchar(33)%2bchar(126)%2bchar(33)))
2019-01-20 16:35:51,705 [cheetah][Thread:53][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:35:52,299 [cheetah][Thread:21][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:35:52,877 [cheetah][Thread:10][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:35:53,408 [cheetah][Thread:21][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:35:53,596 [cheetah][Thread:70][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:35:54,158 [cheetah][Thread:53][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:35:54,424 [cheetah][Thread:70][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:35:54,612 [cheetah][Thread:10][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:35:54,830 [cheetah][Thread:22][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:35:55,080 [cheetah][Thread:10][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:35:55,284 [cheetah][Thread:22][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:35:55,471 [cheetah][Thread:10][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:35:55,659 [cheetah][Thread:71][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:55:22,989 [cheetah][Thread:71][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:55:23,551 [cheetah][Thread:53][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:55:24,583 [cheetah][Thread:24][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:55:26,161 [cheetah][Thread:22][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:55:27,692 [cheetah][Thread:10][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:55:29,192 [cheetah][Thread:71][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:55:29,755 [cheetah][Thread:21][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:55:31,286 [cheetah][Thread:22][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:55:31,848 [cheetah][Thread:24][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:55:32,395 [cheetah][Thread:70][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:55:32,958 [cheetah][Thread:24][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:55:33,520 [cheetah][Thread:22][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:55:34,067 [cheetah][Thread:24][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:55:34,645 [cheetah][Thread:71][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 16:55:35,192 [cheetah][Thread:21][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:15:05,085 [cheetah][Thread:21][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:15:05,257 [cheetah][Thread:10][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:15:05,538 [cheetah][Thread:53][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:15:06,179 [cheetah][Thread:22][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:15:06,538 [cheetah][Thread:22][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:15:06,897 [cheetah][Thread:10][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:15:07,054 [cheetah][Thread:71][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:15:07,444 [cheetah][Thread:10][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:15:07,616 [cheetah][Thread:53][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:15:07,757 [cheetah][Thread:10][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:15:07,913 [cheetah][Thread:24][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:15:08,054 [cheetah][Thread:70][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:15:08,210 [cheetah][Thread:71][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:15:08,366 [cheetah][Thread:53][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:15:08,507 [cheetah][Thread:24][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:34:53,384 [cheetah][Thread:53][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:34:53,525 [cheetah][Thread:71][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:34:53,806 [cheetah][Thread:10][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:34:54,244 [cheetah][Thread:21][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:34:54,869 [cheetah][Thread:10][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:34:55,290 [cheetah][Thread:10][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:34:55,431 [cheetah][Thread:10][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:34:55,822 [cheetah][Thread:24][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:34:55,978 [cheetah][Thread:70][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:34:56,134 [cheetah][Thread:22][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:34:56,275 [cheetah][Thread:70][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:34:56,415 [cheetah][Thread:22][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:34:56,556 [cheetah][Thread:53][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:34:56,712 [cheetah][Thread:10][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:34:56,853 [cheetah][Thread:71][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:54:54,465 [cheetah][Thread:70][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:54:55,074 [cheetah][Thread:10][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:54:55,699 [cheetah][Thread:53][ERROR] DotNetNuke.Entities.Urls.UrlRewriterUtils - System.Exception: Illegal request exception : TabId parameters in query string, but invalid TabId requested : https://www.pensioenfondshaskoningdhv.nl/LinkClick.aspx?fileticket=cNoEITV4h2g=&portalid=1&mid=771&language=en-US&tabid=%2f**%2fcOnVeRt(int%2c(char(33)%2bchar(126)%2bchar(33)%2b(char(65)%2bchar(66)%2bchar(67)%2bchar(49)%2bchar(52)%2bchar(53)%2bchar(90)%2bchar(81)%2bchar(54)%2bchar(50)%2bchar(68)%2bchar(87)%2bchar(81)%2bchar(65)%2bchar(70)%2bchar(80)%2bchar(79)%2bchar(73)%2bchar(89)%2bchar(67)%2bchar(70)%2bchar(68))%2bchar(33)%2bchar(126)%2bchar(33)))
2019-01-20 17:54:56,215 [cheetah][Thread:70][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:54:58,090 [cheetah][Thread:71][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:54:59,996 [cheetah][Thread:71][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:55:01,933 [cheetah][Thread:53][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:55:02,543 [cheetah][Thread:21][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:55:04,465 [cheetah][Thread:21][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:55:05,090 [cheetah][Thread:24][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:55:05,699 [cheetah][Thread:22][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:55:06,293 [cheetah][Thread:24][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:55:06,902 [cheetah][Thread:22][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:55:07,512 [cheetah][Thread:71][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:55:08,121 [cheetah][Thread:21][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 17:55:08,715 [cheetah][Thread:22][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:14:33,889 [cheetah][Thread:53][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:14:33,983 [cheetah][Thread:24][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:14:34,170 [cheetah][Thread:71][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:14:34,451 [cheetah][Thread:10][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:14:34,686 [cheetah][Thread:70][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:14:34,904 [cheetah][Thread:10][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:14:35,014 [cheetah][Thread:24][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:14:35,264 [cheetah][Thread:53][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:14:35,420 [cheetah][Thread:71][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:14:35,529 [cheetah][Thread:53][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:14:35,639 [cheetah][Thread:71][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:14:35,748 [cheetah][Thread:53][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:14:35,858 [cheetah][Thread:71][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:14:35,967 [cheetah][Thread:71][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:14:36,061 [cheetah][Thread:22][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:54:20,956 [cheetah][Thread:22][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:54:21,112 [cheetah][Thread:71][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:54:21,393 [cheetah][Thread:70][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:54:21,800 [cheetah][Thread:22][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:54:22,143 [cheetah][Thread:70][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:54:22,503 [cheetah][Thread:53][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:54:22,659 [cheetah][Thread:10][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:54:23,019 [cheetah][Thread:53][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:54:23,206 [cheetah][Thread:22][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:54:23,347 [cheetah][Thread:53][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:54:23,487 [cheetah][Thread:22][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:54:23,643 [cheetah][Thread:53][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:54:23,784 [cheetah][Thread:22][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:54:23,925 [cheetah][Thread:24][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 18:54:24,065 [cheetah][Thread:10][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-20 19:31:46,210 [cheetah][Thread:71][FATAL] DotNetNuke.Framework.PageBase - An error has occurred while loading page.
System.Web.HttpException (0x80004005): The state information is invalid for this page and might be corrupted. ---> System.Web.UI.ViewStateException: Invalid viewstate. 
	Client IP: 10.2.20.246
	Port: 23328
	Referer: 
	Path: /Default.aspx
	User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
	ViewState: 7bmaKq83mrXct4Ho5H44gJnl1WJnUJ5EZeVHd4vmxfkGiqnGH4NvDcY8klb6nF/TDYon92EUxIF 4VwuhaQVcp9ftzc3yj8eL8i5J4tljToxH2FAoM kMYrsVfXCb c0Oasdx6zwTfVAwssF0QLz2ry0oNL7ZRTmvHO5v0I9bYEXBXYaiytxPUizJXKSbD1AwflHOK47B yo0yUNswDsCtimt16n21DoHg jFjPqYnZVxBj0nPZiDu3X0hGVz8jao56aWN0S2RLbEndmeNXF0s2PrpduYAf JmtcrwakA  byqVNHeUtTh4Cl8MpliexSVHWSKwvi0YqeFCOiTsQWbh5LAkC2381OAcJcRtN8eMI63SIMDWp2L3v2rAeoH  NsM37g== ---> System.FormatException: Invalid length for a Base-64 char array or string.
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at System.Web.UI.ObjectStateFormatter.Deserialize(String inputString, Purpose purpose)
   at System.Web.UI.Util.DeserializeWithAssert(IStateFormatter2 formatter, String serializedState, Purpose purpose)
   at System.Web.UI.HiddenFieldPageStatePersister.Load()
   --- End of inner exception stack trace ---
   at System.Web.UI.ViewStateException.ThrowError(Exception inner, String persistedState, String errorPageMessage, Boolean macValidationError)
   at System.Web.UI.HiddenFieldPageStatePersister.Load()
   at System.Web.UI.Page.LoadPageStateFromPersistenceMedium()
   at System.Web.UI.Page.LoadAllState()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
2019-01-20 19:31:46,210 [cheetah][Thread:71][ERROR] DotNetNuke.Services.Exceptions.Exceptions - ~/Default.aspx?tabid=243&error=An unexpected error has occurred&content=0
System.Web.HttpException (0x80004005): The state information is invalid for this page and might be corrupted. ---> System.Web.UI.ViewStateException: Invalid viewstate. 
	Client IP: 10.2.20.246
	Port: 23328
	Referer: 
	Path: /Default.aspx
	User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
	ViewState: 7bmaKq83mrXct4Ho5H44gJnl1WJnUJ5EZeVHd4vmxfkGiqnGH4NvDcY8klb6nF/TDYon92EUxIF 4VwuhaQVcp9ftzc3yj8eL8i5J4tljToxH2FAoM kMYrsVfXCb c0Oasdx6zwTfVAwssF0QLz2ry0oNL7ZRTmvHO5v0I9bYEXBXYaiytxPUizJXKSbD1AwflHOK47B yo0yUNswDsCtimt16n21DoHg jFjPqYnZVxBj0nPZiDu3X0hGVz8jao56aWN0S2RLbEndmeNXF0s2PrpduYAf JmtcrwakA  byqVNHeUtTh4Cl8MpliexSVHWSKwvi0YqeFCOiTsQWbh5LAkC2381OAcJcRtN8eMI63SIMDWp2L3v2rAeoH  NsM37g== ---> System.FormatException: Invalid length for a Base-64 char array or string.
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at System.Web.UI.ObjectStateFormatter.Deserialize(String inputString, Purpose purpose)
   at System.Web.UI.Util.DeserializeWithAssert(IStateFormatter2 formatter, String serializedState, Purpose purpose)
   at System.Web.UI.HiddenFieldPageStatePersister.Load()
   --- End of inner exception stack trace ---
   at System.Web.UI.ViewStateException.ThrowError(Exception inner, String persistedState, String errorPageMessage, Boolean macValidationError)
   at System.Web.UI.HiddenFieldPageStatePersister.Load()
   at System.Web.UI.Page.LoadPageStateFromPersistenceMedium()
   at System.Web.UI.Page.LoadAllState()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
2019-01-20 19:31:49,710 [cheetah][Thread:22][FATAL] DotNetNuke.Framework.PageBase - An error has occurred while loading page.
System.Web.HttpException (0x80004005): The state information is invalid for this page and might be corrupted. ---> System.Web.UI.ViewStateException: Invalid viewstate. 
	Client IP: 10.2.20.246
	Port: 7261
	Referer: 
	Path: /Default.aspx
	User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
	ViewState: TxEoLSYbGmOJt/8W3ogD024dSlXs0T6z0m9yujaQlcNg5/VcEMdBNeby2g3vtG1AubBSo0hTe R1KXd1lS3WFCAclzUAWkefEIbX8g== ---> System.FormatException: Invalid length for a Base-64 char array or string.
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at System.Web.UI.ObjectStateFormatter.Deserialize(String inputString, Purpose purpose)
   at System.Web.UI.Util.DeserializeWithAssert(IStateFormatter2 formatter, String serializedState, Purpose purpose)
   at System.Web.UI.HiddenFieldPageStatePersister.Load()
   --- End of inner exception stack trace ---
   at System.Web.UI.ViewStateException.ThrowError(Exception inner, String persistedState, String errorPageMessage, Boolean macValidationError)
   at System.Web.UI.HiddenFieldPageStatePersister.Load()
   at System.Web.UI.Page.LoadPageStateFromPersistenceMedium()
   at System.Web.UI.Page.LoadAllState()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
2019-01-20 19:31:49,710 [cheetah][Thread:22][ERROR] DotNetNuke.Services.Exceptions.Exceptions - ~/Default.aspx?tabid=426&error=An unexpected error has occurred&content=0
System.Web.HttpException (0x80004005): The state information is invalid for this page and might be corrupted. ---> System.Web.UI.ViewStateException: Invalid viewstate. 
	Client IP: 10.2.20.246
	Port: 7261
	Referer: 
	Path: /Default.aspx
	User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
	ViewState: TxEoLSYbGmOJt/8W3ogD024dSlXs0T6z0m9yujaQlcNg5/VcEMdBNeby2g3vtG1AubBSo0hTe R1KXd1lS3WFCAclzUAWkefEIbX8g== ---> System.FormatException: Invalid length for a Base-64 char array or string.
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at System.Web.UI.ObjectStateFormatter.Deserialize(String inputString, Purpose purpose)
   at System.Web.UI.Util.DeserializeWithAssert(IStateFormatter2 formatter, String serializedState, Purpose purpose)
   at System.Web.UI.HiddenFieldPageStatePersister.Load()
   --- End of inner exception stack trace ---
   at System.Web.UI.ViewStateException.ThrowError(Exception inner, String persistedState, String errorPageMessage, Boolean macValidationError)
   at System.Web.UI.HiddenFieldPageStatePersister.Load()
   at System.Web.UI.Page.LoadPageStateFromPersistenceMedium()
   at System.Web.UI.Page.LoadAllState()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
2019-01-20 20:38:09,765 [cheetah][Thread:11][ERROR] DotNetNuke.Data.PetaPoco.PetaPocoHelper - [3] Error executing SQL: ;Exec dbo.GetSchedule @0
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
2019-01-20 20:38:09,765 [cheetah][Thread:63][ERROR] DotNetNuke.Data.PetaPoco.PetaPocoHelper - [3] Error executing SQL: ;Exec dbo.GetSchedule @0
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
2019-01-20 20:38:09,765 [cheetah][Thread:11][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteReader(String procedureName, Object[] commandParameters)
   at DotNetNuke.Services.Scheduling.SchedulingController.GetSchedule(String Server)
   at DotNetNuke.Services.Scheduling.Scheduler.CoreScheduler.LoadQueueFromTimer()
   at DotNetNuke.Services.Scheduling.Scheduler.CoreScheduler.Start()
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20
2019-01-20 20:38:09,765 [cheetah][Thread:63][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteReader(String procedureName, Object[] commandParameters)
   at DotNetNuke.Services.Scheduling.SchedulingController.GetSchedule(String Server)
   at DotNetNuke.Services.Scheduling.Scheduler.CoreScheduler.LoadQueueFromTimer()
   at DotNetNuke.Services.Scheduling.Scheduler.CoreScheduler.Start()
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20
2019-01-20 20:38:09,765 [cheetah][Thread:11][ERROR] DotNetNuke.Data.PetaPoco.PetaPocoHelper - [1] Error executing SQL: ;Exec dbo.AddException @0, @1, @2, @3, @4, @5
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
2019-01-20 20:38:09,765 [cheetah][Thread:11][ERROR] DotNetNuke.Services.Log.EventLog.DBLoggingProvider - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at PetaPoco.Database.Execute(String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteNonQuery(String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteNonQuery(String procedureName, Object[] commandParameters)
   at DotNetNuke.Data.DataProvider.AddLog(String logGUID, String logTypeKey, Int32 logUserID, String logUserName, Int32 logPortalID, String logPortalName, DateTime logCreateDate, String logServerName, String logProperties, Int32 logConfigID, ExceptionInfo exception, Boolean notificationActive)
   at DotNetNuke.Services.Log.EventLog.DBLoggingProvider.WriteLog(LogQueueItem logQueueItem)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20
2019-01-20 20:38:09,765 [cheetah][Thread:70][ERROR] DotNetNuke.Data.PetaPoco.PetaPocoHelper - [3] Error executing SQL: ;Exec dbo.GetScheduleNextTask @0
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
2019-01-20 20:38:09,781 [cheetah][Thread:70][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteReader(String procedureName, Object[] commandParameters)
   at DotNetNuke.Services.Scheduling.SchedulingController.GetNextScheduledTask(String Server)
   at DotNetNuke.Services.Scheduling.SchedulingProvider.set_ScheduleLastPolled(DateTime value)
   at DotNetNuke.Common.Initialize.RunSchedule(HttpRequest request)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20
2019-01-20 20:38:09,765 [cheetah][Thread:22][ERROR] DotNetNuke.Data.PetaPoco.PetaPocoHelper - [3] Error executing SQL: ;Exec dbo.GetScheduleNextTask @0
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
2019-01-20 20:38:09,781 [cheetah][Thread:22][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteReader(String procedureName, Object[] commandParameters)
   at DotNetNuke.Services.Scheduling.SchedulingController.GetNextScheduledTask(String Server)
   at DotNetNuke.Services.Scheduling.SchedulingProvider.set_ScheduleLastPolled(DateTime value)
   at DotNetNuke.Common.Initialize.RunSchedule(HttpRequest request)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20
2019-01-20 20:38:09,765 [cheetah][Thread:63][ERROR] DotNetNuke.Data.PetaPoco.PetaPocoHelper - [1] Error executing SQL: ;Exec dbo.AddException @0, @1, @2, @3, @4, @5
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
2019-01-20 20:38:09,781 [cheetah][Thread:63][ERROR] DotNetNuke.Services.Log.EventLog.DBLoggingProvider - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at PetaPoco.Database.Execute(String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteNonQuery(String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteNonQuery(String procedureName, Object[] commandParameters)
   at DotNetNuke.Data.DataProvider.AddLog(String logGUID, String logTypeKey, Int32 logUserID, String logUserName, Int32 logPortalID, String logPortalName, DateTime logCreateDate, String logServerName, String logProperties, Int32 logConfigID, ExceptionInfo exception, Boolean notificationActive)
   at DotNetNuke.Services.Log.EventLog.DBLoggingProvider.WriteLog(LogQueueItem logQueueItem)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20
2019-01-20 20:38:09,781 [cheetah][Thread:22][ERROR] DotNetNuke.Data.PetaPoco.PetaPocoHelper - [1] Error executing SQL: ;Exec dbo.AddException @0, @1, @2, @3, @4, @5
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
2019-01-20 20:38:09,781 [cheetah][Thread:22][ERROR] DotNetNuke.Services.Log.EventLog.DBLoggingProvider - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at PetaPoco.Database.Execute(String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteNonQuery(String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteNonQuery(String procedureName, Object[] commandParameters)
   at DotNetNuke.Data.DataProvider.AddLog(String logGUID, String logTypeKey, Int32 logUserID, String logUserName, Int32 logPortalID, String logPortalName, DateTime logCreateDate, String logServerName, String logProperties, Int32 logConfigID, ExceptionInfo exception, Boolean notificationActive)
   at DotNetNuke.Services.Log.EventLog.DBLoggingProvider.WriteLog(LogQueueItem logQueueItem)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20
2019-01-20 20:38:09,781 [cheetah][Thread:70][ERROR] DotNetNuke.Data.PetaPoco.PetaPocoHelper - [1] Error executing SQL: ;Exec dbo.AddException @0, @1, @2, @3, @4, @5
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
2019-01-20 20:38:09,781 [cheetah][Thread:70][ERROR] DotNetNuke.Services.Log.EventLog.DBLoggingProvider - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at PetaPoco.Database.Execute(String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteNonQuery(String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteNonQuery(String procedureName, Object[] commandParameters)
   at DotNetNuke.Data.DataProvider.AddLog(String logGUID, String logTypeKey, Int32 logUserID, String logUserName, Int32 logPortalID, String logPortalName, DateTime logCreateDate, String logServerName, String logProperties, Int32 logConfigID, ExceptionInfo exception, Boolean notificationActive)
   at DotNetNuke.Services.Log.EventLog.DBLoggingProvider.WriteLog(LogQueueItem logQueueItem)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20
2019-01-20 20:38:09,812 [cheetah][Thread:22][ERROR] DotNetNuke.Services.Log.EventLog.LogController - System.Exception: Error on 'D:\LIVE\SPHDHV\Pensioenfonds\DnnHost.090200\Web\Install\Install.htm': See InnerException for details. ---> System.ComponentModel.Win32Exception: The process cannot access the file because it is being used by another process
   --- End of inner exception stack trace ---
   at SchwabenCode.QuickIO.Internal.InternalQuickIOCommon.NativeExceptionMapping(String path, Int32 errorCode)
   at SchwabenCode.QuickIO.QuickIOFile.OpenFileStream(QuickIOPathInfo pathInfo, FileAccess fileAccess, FileMode fileOption, FileShare shareMode, Int32 buffer)
   at SchwabenCode.QuickIO.QuickIOFile.OpenText(QuickIOPathInfo pathInfo)
   at DotNetNuke.Common.Utilities.FileSystemUtils.ReadFile(String filePath)
   at DotNetNuke.Common.Utilities.HtmlUtils.WriteHeader(HttpResponse response, String mode)
   at DotNetNuke.Services.Log.EventLog.DBLoggingProvider.WriteError(LogTypeConfigInfo logTypeConfigInfo, Exception exc, String header, String message)
   at DotNetNuke.Services.Log.EventLog.DBLoggingProvider.WriteLog(LogQueueItem logQueueItem)
   at DotNetNuke.Services.Log.EventLog.DBLoggingProvider.AddLog(LogInfo logInfo)
   at DotNetNuke.Services.Log.EventLog.LogController.AddLog(LogInfo logInfo)
2019-01-20 20:38:09,843 [cheetah][Thread:70][ERROR] DotNetNuke.Services.Log.EventLog.LogController - System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Web.HttpResponse.AbortCurrentThread()
   at DotNetNuke.Services.Log.EventLog.DBLoggingProvider.WriteError(LogTypeConfigInfo logTypeConfigInfo, Exception exc, String header, String message)
   at DotNetNuke.Services.Log.EventLog.DBLoggingProvider.WriteLog(LogQueueItem logQueueItem)
   at DotNetNuke.Services.Log.EventLog.DBLoggingProvider.AddLog(LogInfo logInfo)
   at DotNetNuke.Services.Log.EventLog.LogController.AddLog(LogInfo logInfo)
2019-01-20 20:38:10,687 [cheetah][Thread:18][ERROR] DotNetNuke.Data.PetaPoco.PetaPocoHelper - [3] Error executing SQL: ;Exec dbo.GetSchedule @0
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
2019-01-20 20:38:10,703 [cheetah][Thread:18][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteReader(String procedureName, Object[] commandParameters)
   at DotNetNuke.Services.Scheduling.SchedulingController.GetSchedule(String Server)
   at DotNetNuke.Services.Scheduling.Scheduler.CoreScheduler.LoadQueueFromTimer()
   at DotNetNuke.Services.Scheduling.Scheduler.CoreScheduler.Start()
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20
2019-01-20 20:38:10,703 [cheetah][Thread:18][ERROR] DotNetNuke.Data.PetaPoco.PetaPocoHelper - [1] Error executing SQL: ;Exec dbo.AddException @0, @1, @2, @3, @4, @5
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
2019-01-20 20:38:10,703 [cheetah][Thread:18][ERROR] DotNetNuke.Services.Log.EventLog.DBLoggingProvider - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at PetaPoco.Database.Execute(String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteNonQuery(String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteNonQuery(String procedureName, Object[] commandParameters)
   at DotNetNuke.Data.DataProvider.AddLog(String logGUID, String logTypeKey, Int32 logUserID, String logUserName, Int32 logPortalID, String logPortalName, DateTime logCreateDate, String logServerName, String logProperties, Int32 logConfigID, ExceptionInfo exception, Boolean notificationActive)
   at DotNetNuke.Services.Log.EventLog.DBLoggingProvider.WriteLog(LogQueueItem logQueueItem)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20
2019-01-20 20:38:10,687 [cheetah][Thread:10][ERROR] DotNetNuke.Data.PetaPoco.PetaPocoHelper - [3] Error executing SQL: ;Exec dbo.GetScheduleNextTask @0
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
2019-01-20 20:38:10,703 [cheetah][Thread:10][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteReader(String procedureName, Object[] commandParameters)
   at DotNetNuke.Services.Scheduling.SchedulingController.GetNextScheduledTask(String Server)
   at DotNetNuke.Services.Scheduling.SchedulingProvider.set_ScheduleLastPolled(DateTime value)
   at DotNetNuke.Common.Initialize.RunSchedule(HttpRequest request)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20
2019-01-20 20:38:10,703 [cheetah][Thread:10][ERROR] DotNetNuke.Data.PetaPoco.PetaPocoHelper - [1] Error executing SQL: ;Exec dbo.AddException @0, @1, @2, @3, @4, @5
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
2019-01-20 20:38:10,703 [cheetah][Thread:10][ERROR] DotNetNuke.Services.Log.EventLog.DBLoggingProvider - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at PetaPoco.Database.Execute(String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteNonQuery(String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteNonQuery(String procedureName, Object[] commandParameters)
   at DotNetNuke.Data.DataProvider.AddLog(String logGUID, String logTypeKey, Int32 logUserID, String logUserName, Int32 logPortalID, String logPortalName, DateTime logCreateDate, String logServerName, String logProperties, Int32 logConfigID, ExceptionInfo exception, Boolean notificationActive)
   at DotNetNuke.Services.Log.EventLog.DBLoggingProvider.WriteLog(LogQueueItem logQueueItem)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20
2019-01-20 20:38:10,703 [cheetah][Thread:10][ERROR] DotNetNuke.Services.Log.EventLog.LogController - System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Web.HttpResponse.AbortCurrentThread()
   at DotNetNuke.Services.Log.EventLog.DBLoggingProvider.WriteError(LogTypeConfigInfo logTypeConfigInfo, Exception exc, String header, String message)
   at DotNetNuke.Services.Log.EventLog.DBLoggingProvider.WriteLog(LogQueueItem logQueueItem)
   at DotNetNuke.Services.Log.EventLog.DBLoggingProvider.AddLog(LogInfo logInfo)
   at DotNetNuke.Services.Log.EventLog.LogController.AddLog(LogInfo logInfo)
2019-01-20 20:38:10,718 [cheetah][Thread:9][ERROR] DotNetNuke.Data.PetaPoco.PetaPocoHelper - [3] Error executing SQL: ;Exec dbo.GetSchedule @0
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
2019-01-20 20:38:10,734 [cheetah][Thread:9][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteReader(String procedureName, Object[] commandParameters)
   at DotNetNuke.Services.Scheduling.SchedulingController.GetSchedule(String Server)
   at DotNetNuke.Services.Scheduling.Scheduler.CoreScheduler.LoadQueueFromTimer()
   at DotNetNuke.Services.Scheduling.Scheduler.CoreScheduler.Start()
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20
2019-01-20 20:38:10,734 [cheetah][Thread:22][ERROR] DotNetNuke.Data.PetaPoco.PetaPocoHelper - [3] Error executing SQL: ;Exec dbo.GetScheduleNextTask @0
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
2019-01-20 20:38:10,734 [cheetah][Thread:22][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteReader(String procedureName, Object[] commandParameters)
   at DotNetNuke.Services.Scheduling.SchedulingController.GetNextScheduledTask(String Server)
   at DotNetNuke.Services.Scheduling.SchedulingProvider.set_ScheduleLastPolled(DateTime value)
   at DotNetNuke.Common.Initialize.RunSchedule(HttpRequest request)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20
2019-01-20 20:38:10,734 [cheetah][Thread:22][ERROR] DotNetNuke.Data.PetaPoco.PetaPocoHelper - [1] Error executing SQL: ;Exec dbo.AddException @0, @1, @2, @3, @4, @5
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
2019-01-20 20:38:10,734 [cheetah][Thread:22][ERROR] DotNetNuke.Services.Log.EventLog.DBLoggingProvider - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at PetaPoco.Database.Execute(String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteNonQuery(String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteNonQuery(String procedureName, Object[] commandParameters)
   at DotNetNuke.Data.DataProvider.AddLog(String logGUID, String logTypeKey, Int32 logUserID, String logUserName, Int32 logPortalID, String logPortalName, DateTime logCreateDate, String logServerName, String logProperties, Int32 logConfigID, ExceptionInfo exception, Boolean notificationActive)
   at DotNetNuke.Services.Log.EventLog.DBLoggingProvider.WriteLog(LogQueueItem logQueueItem)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20
2019-01-20 20:38:10,734 [cheetah][Thread:22][ERROR] DotNetNuke.Services.Log.EventLog.LogController - System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Web.HttpResponse.AbortCurrentThread()
   at DotNetNuke.Services.Log.EventLog.DBLoggingProvider.WriteError(LogTypeConfigInfo logTypeConfigInfo, Exception exc, String header, String message)
   at DotNetNuke.Services.Log.EventLog.DBLoggingProvider.WriteLog(LogQueueItem logQueueItem)
   at DotNetNuke.Services.Log.EventLog.DBLoggingProvider.AddLog(LogInfo logInfo)
   at DotNetNuke.Services.Log.EventLog.LogController.AddLog(LogInfo logInfo)
2019-01-20 20:38:10,734 [cheetah][Thread:9][ERROR] DotNetNuke.Data.PetaPoco.PetaPocoHelper - [1] Error executing SQL: ;Exec dbo.AddException @0, @1, @2, @3, @4, @5
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
2019-01-20 20:38:10,734 [cheetah][Thread:9][ERROR] DotNetNuke.Services.Log.EventLog.DBLoggingProvider - System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at PetaPoco.Database.Execute(String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteNonQuery(String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteNonQuery(String procedureName, Object[] commandParameters)
   at DotNetNuke.Data.DataProvider.AddLog(String logGUID, String logTypeKey, Int32 logUserID, String logUserName, Int32 logPortalID, String logPortalName, DateTime logCreateDate, String logServerName, String logProperties, Int32 logConfigID, ExceptionInfo exception, Boolean notificationActive)
   at DotNetNuke.Services.Log.EventLog.DBLoggingProvider.WriteLog(LogQueueItem logQueueItem)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20
