2019-01-01 07:11:44,569 [cheetah][Thread:83][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-01 07:11:46,147 [cheetah][Thread:59][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-01 07:11:47,741 [cheetah][Thread:59][ERROR] DotNetNuke.Entities.Urls.UrlRewriterUtils - System.Exception: Illegal request exception : TabId parameters in query string, but invalid TabId requested : https://www.pensioenfondshaskoningdhv.nl/LinkClick.aspx?fileticket=cNoEITV4h2g%3D&portalid=1&mid=771&language=en-US&tabid=%2f**%2fcOnVeRt(int%2c(char(33)%2bchar(126)%2bchar(33)%2b(char(65)%2bchar(66)%2bchar(67)%2bchar(49)%2bchar(52)%2bchar(53)%2bchar(90)%2bchar(81)%2bchar(54)%2bchar(50)%2bchar(68)%2bchar(87)%2bchar(81)%2bchar(65)%2bchar(70)%2bchar(80)%2bchar(79)%2bchar(73)%2bchar(89)%2bchar(67)%2bchar(70)%2bchar(68))%2bchar(33)%2bchar(126)%2bchar(33)))
2019-01-01 07:11:49,022 [cheetah][Thread:85][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-01 07:12:12,148 [cheetah][Thread:85][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-01 07:12:16,507 [cheetah][Thread:85][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-01 07:12:21,023 [cheetah][Thread:59][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-01 07:12:22,569 [cheetah][Thread:112][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-01 07:12:27,351 [cheetah][Thread:59][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-01 07:24:25,540 [cheetah][Thread:112][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-01 07:24:25,665 [cheetah][Thread:30][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-01 07:24:25,899 [cheetah][Thread:30][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-01 07:24:26,211 [cheetah][Thread:83][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-01 07:24:26,461 [cheetah][Thread:30][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-01 07:24:26,711 [cheetah][Thread:30][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-01 07:24:26,836 [cheetah][Thread:85][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-01 07:24:27,133 [cheetah][Thread:83][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-01 07:24:27,477 [cheetah][Thread:112][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-01 07:24:27,602 [cheetah][Thread:30][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-01 07:24:27,727 [cheetah][Thread:85][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-01 07:24:27,836 [cheetah][Thread:83][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-01 07:24:27,962 [cheetah][Thread:59][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-01 07:24:28,071 [cheetah][Thread:83][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-01 07:24:28,211 [cheetah][Thread:59][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource Not Found: - FileID=-1
System.Web.HttpException (0x80004005): Resource Not Found
2019-01-01 13:54:04,726 [cheetah][Thread:24][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.Web.HttpException (0x80004005): Cannot redirect after HTTP headers have been sent.
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)
   at Sphdhv.DnnWebApi.Controllers.AuthenticationController.<VerifyToken>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2019-01-01 13:54:04,788 [cheetah][Thread:24][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.Web.HttpException (0x80004005): Cannot redirect after HTTP headers have been sent.
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)
   at Sphdhv.DnnWebApi.Controllers.AuthenticationController.<VerifyToken>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2019-01-01 13:54:04,804 [cheetah][Thread:24][FATAL] DotNetNuke.Web.Common.Internal.DotNetNukeHttpApplication - System.Web.HttpException (0x80004005): Server cannot set status after HTTP headers have been sent.
   at System.Web.HttpResponse.set_StatusCode(Int32 value)
   at System.Web.Http.WebHost.HttpControllerHandler.<CopyResponseStatusAndHeadersAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.WebHost.HttpControllerHandler.<CopyResponseAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.WebHost.HttpControllerHandler.<ProcessRequestAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at System.Web.HttpApplication.CallHandlerExecutionStep.InvokeEndHandler(IAsyncResult ar)
   at System.Web.HttpApplication.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar)
2019-01-01 17:36:26,346 [cheetah][Thread:24][ERROR] DotNetNuke.Services.Exceptions.Exceptions - Resource niet gevonden: - 
System.Web.HttpException (0x80004005): Resource niet gevonden
2019-01-01 19:32:27,062 [cheetah][Thread:30][FATAL] DotNetNuke.Web.Common.Internal.DotNetNukeHttpApplication - System.Web.HttpException (0x80004005): This is an invalid webresource request.
   at System.Web.Handlers.AssemblyResourceLoader.System.Web.IHttpHandler.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
